### ISSUE TITLE
Porting to @galaxysys

### ISSUE THREAD

**Issue by connor557** [kxes/tugger-system#1]
I am interested in porting this to Marvell XScale for use with @galaxysys. I have great interest in your OS framework and think it would be great as a mobile phone/PDA system. Please contact me through email if you are at all interested.

**Comment by joshiggins** [comment]
Hi Connor. The tool chain is more or less an automated version of [Linux From Scratch](http://www.linuxfromscratch.org/). If you know how to cross compile for XScale it surely would be possible to port it. Right now there is not really enough effort for me to look in to it, but please fork! Best to ping me on here.

**Comment by connor557** [comment]
Well, I'll look into it. I've decided to go towards a more Palm-based system, creating a central archive that installs a set of PRCs from a repo.
